# Generated by Django 5.2.6 on 2025-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Porject_made_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio/images/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
